name: Test

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Start PostgreSQL
        run: |
          sudo systemctl start postgresql
          sudo -u postgres createuser -s decision_matrix
          sudo -u postgres createdb -O decision_matrix decision_matrix
          sudo -u postgres psql -c "ALTER USER decision_matrix PASSWORD 'decision_matrix_password';"
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run checks
        run: ./gradlew check
